import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "reference/ospi-platform-api",
    },
    {
      type: "category",
      label: "health",
      items: [
        {
          type: "doc",
          id: "reference/health-controller-check",
          label: "Health check",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "audit",
      items: [
        {
          type: "doc",
          id: "reference/audit-controller-list",
          label: "List audit-log entries",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/audit-controller-seal-chain",
          label: "Seal the audit-log hash chain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/audit-controller-verify-chain",
          label: "Verify the audit-log hash chain",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "auth",
      items: [
        {
          type: "doc",
          id: "reference/auth-controller-register",
          label: "Register a new organization + owner user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-login",
          label: "Log in with email + password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-refresh",
          label: "Exchange a refresh token for a new access token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-logout",
          label: "Log out this device",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-switch-organization",
          label: "Switch the active organization on this session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-list-memberships",
          label: "List the caller's organization memberships",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/auth-controller-accept-membership",
          label: "Accept a pending organization membership invitation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-switch-entity",
          label: "Switch the active legal Entity on this session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-list-entity-memberships",
          label: "List the caller's entity memberships",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/auth-controller-accept-entity-membership",
          label: "Accept a pending entity membership invitation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-logout-all",
          label: "Log out from all devices",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-list-sessions",
          label: "List the caller's active sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/auth-controller-revoke-session",
          label: "Revoke a specific session",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/auth-controller-create-api-client",
          label: "Create an M2M API client + key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-enroll-mfa",
          label: "Start TOTP MFA enrollment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-confirm-mfa",
          label: "Confirm TOTP MFA enrollment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-disable-mfa",
          label: "Disable MFA",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-regenerate-mfa-backup-codes",
          label: "Regenerate MFA backup codes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-mfa-status",
          label: "Get MFA status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "roles",
      items: [
        {
          type: "doc",
          id: "reference/roles-controller-list-permissions",
          label: "List the full permission catalogue",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/roles-controller-create",
          label: "Create a custom role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/roles-controller-list",
          label: "List the organization's roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/roles-controller-list-for-user",
          label: "List a user's assigned roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/roles-controller-assign",
          label: "Assign a role to a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/roles-controller-revoke",
          label: "Revoke a role from a user",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "organizations",
      items: [
        {
          type: "doc",
          id: "reference/organizations-controller-get-own",
          label: "Get the caller's own organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-update",
          label: "Update an organization",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-set-commission-rate",
          label: "Set (or clear) an organization's platform commission rate override",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-list-users",
          label: "List the organization's users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-invite-user",
          label: "Invite a user to the organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-list-roles",
          label: "List the organization's roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-suspend-member",
          label: "Suspend a member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-reactivate-member",
          label: "Reactivate a suspended member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-remove-member",
          label: "Remove a member",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-unlock-member",
          label: "Unlock a locked-out member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-request-domain-verification",
          label: "Request domain verification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-list-domain-verifications",
          label: "List domain verifications for an organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-verify-domain",
          label: "Verify a domain",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "partner-search",
      items: [
        {
          type: "doc",
          id: "reference/partner-search-controller-search",
          label: "Search publicly discoverable organizations",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "entities",
      items: [
        {
          type: "doc",
          id: "reference/entities-controller-list",
          label: "List the organization's legal Entities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/entities-controller-create",
          label: "Create a legal Entity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/entities-controller-update",
          label: "Update a legal Entity",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/entities-controller-list-users",
          label: "List an Entity's members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/entities-controller-invite-user",
          label: "Invite a user to an Entity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/entities-controller-suspend-member",
          label: "Suspend an Entity member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/entities-controller-reactivate-member",
          label: "Reactivate a suspended Entity member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/entities-controller-remove-member",
          label: "Remove an Entity member",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "identity",
      items: [
        {
          type: "doc",
          id: "reference/identity-controller-create-producer",
          label: "Create a Producer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-list-producers",
          label: "List producers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/identity-controller-issue-producer-code",
          label: "Issue a Producer Code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-issue-ospi-identity",
          label: "Issue a new OSPI Identity code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-validate",
          label: "Validate an OSPI Code's structure",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-lookup",
          label: "Look up an OSPI Code",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/identity-controller-retire",
          label: "Retire an OSPI Identity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-suspend",
          label: "Suspend an OSPI Identity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-reactivate",
          label: "Reactivate a suspended OSPI Identity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-get-public-unit-view",
          label: "Public view of a serialized unit (DPP consumer view)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/identity-controller-register-unit-owner",
          label: "Register (or transfer) ownership of a serialized unit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-scan-for-maintenance",
          label: "Scan in to log maintenance on a serialized unit",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "products",
      items: [
        {
          type: "doc",
          id: "reference/products-controller-create",
          label: "Create a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list",
          label: "List products",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-create-bulk",
          label: "Bulk-create products",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-find-one",
          label: "Get a product by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-update",
          label: "Update a product",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/products-controller-validate",
          label: "Validate a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-publish",
          label: "Publish a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-unpublish",
          label: "Unpublish a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-retire",
          label: "Retire a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-recall",
          label: "Recall a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-add-variant",
          label: "Add a variant to a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-variants",
          label: "List a product's variants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-register-serialized-unit",
          label: "Register a serialized unit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-serialized-units",
          label: "List a product's serialized units",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-register-serialized-units-bulk",
          label: "Bulk-register serialized units",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-add-serialized-unit-event",
          label: "Add a serialized unit's event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-serialized-unit-events",
          label: "List a serialized unit's event history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-set-translation",
          label: "Set a per-locale translation",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/products-controller-remove-translation",
          label: "Remove a translation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-translations",
          label: "List a product's translations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-create-relationship",
          label: "Create a product relationship",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-relationships",
          label: "List a product's relationships",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-remove-relationship",
          label: "Remove a product relationship",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/products-controller-create-component",
          label: "Add a BOM component to a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-components",
          label: "List a product's BOM components",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-remove-component",
          label: "Remove a BOM component",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/products-controller-create-version",
          label: "Create a new product version snapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-versions",
          label: "List a product's version history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-get-version",
          label: "Get a single product version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-set-branding",
          label: "Assign (or clear) a product's branding profile",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/products-controller-upsert-compliance-field",
          label: "Create or update a compliance field",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-compliance-fields",
          label: "List a product's compliance fields",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-remove-compliance-field",
          label: "Remove a compliance field",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-successors",
          label: "List a product's successors/replacements",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "categories",
      items: [
        {
          type: "doc",
          id: "reference/categories-controller-create",
          label: "Create a category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/categories-controller-list",
          label: "List categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/categories-controller-list-pending",
          label: "List pending global-category proposals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/categories-controller-approve",
          label: "Approve a global-category proposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/categories-controller-reject",
          label: "Reject a global-category proposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/categories-controller-set-category-compliance-requirement",
          label: "Set a category's DPP compliance requirement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/categories-controller-get-category-compliance-status",
          label: "Get a category's compliance requirement and the caller's own rollup",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "classification",
      items: [
        {
          type: "doc",
          id: "reference/classification-controller-create-attribute-definition",
          label: "Create an attribute definition",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-list-attribute-definitions",
          label: "List attribute definitions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-set-product-attribute-value",
          label: "Set an attribute value on a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-set-variant-attribute-value",
          label: "Set an attribute value on a variant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-verify-attribute-value",
          label: "Verify an attribute value",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-create-scheme",
          label: "Create a classification scheme",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-list-schemes",
          label: "List classification schemes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-add-node",
          label: "Add a node to a classification scheme",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-list-nodes",
          label: "List a scheme's nodes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-assign",
          label: "Assign a product/variant to a classification node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-set-category-attribute-schema",
          label: "Set a category's attribute schema rule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-remove-category-attribute-schema",
          label: "Remove a category's attribute schema rule",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/classification-controller-get-effective-attribute-schema",
          label: "Get a category's effective attribute schema",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-propose-attribute-schema",
          label: "Propose an attribute requirement for a shared category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-list-attribute-schema-proposals-for-category",
          label: "List attribute-schema proposals for a category",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-list-my-attribute-schema-proposals",
          label: "List the caller's own attribute-schema proposals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-get-attribute-schema-proposal",
          label: "Get a single attribute-schema proposal",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-vote-on-attribute-schema-proposal",
          label: "Vote on an attribute-schema proposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-decide-attribute-schema-proposal",
          label: "Decide an attribute-schema proposal",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "units",
      items: [
        {
          type: "doc",
          id: "reference/units-controller-create-category",
          label: "Create a unit category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/units-controller-list-categories",
          label: "List unit categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/units-controller-create-unit",
          label: "Create a unit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/units-controller-list-units",
          label: "List units",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "documents",
      items: [
        {
          type: "doc",
          id: "reference/documents-controller-create",
          label: "Create a document record referencing an external URL",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/documents-controller-list",
          label: "List documents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/documents-controller-upload",
          label: "Upload and store a document file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/documents-controller-find-one",
          label: "Get a document by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/documents-controller-update-metadata",
          label: "Update a document's metadata",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/documents-controller-get-download-url",
          label: "Get a short-lived download URL for a document",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "locations",
      items: [
        {
          type: "doc",
          id: "reference/locations-controller-create",
          label: "Create a location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/locations-controller-list",
          label: "List locations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/locations-controller-list-inventory",
          label: "List inventory at a location",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "inventory",
      items: [
        {
          type: "doc",
          id: "reference/inventory-controller-upsert",
          label: "Set inventory for a product at a location",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/inventory-controller-list",
          label: "List a product's inventory",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "connections",
      items: [
        {
          type: "doc",
          id: "reference/connections-controller-request",
          label: "Request a B2B connection with another organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/connections-controller-list",
          label: "List the caller's connections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/connections-controller-accept",
          label: "Accept a connection request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/connections-controller-reject",
          label: "Reject a connection request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/connections-controller-suspend",
          label: "Suspend an active connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/connections-controller-terminate",
          label: "Terminate a connection permanently",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "sharing",
      items: [
        {
          type: "doc",
          id: "reference/sharing-controller-create",
          label: "Create a sharing grant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/sharing-controller-list",
          label: "List the caller's sharing grants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/sharing-controller-revoke",
          label: "Revoke a sharing grant",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "partner",
      items: [
        {
          type: "doc",
          id: "reference/partner-controller-list-products",
          label: "List a partner organization's shared products",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/partner-controller-create-export",
          label: "Create a bulk export of a partner's shared products",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/partner-controller-get-export",
          label: "Get an export's status/download URL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/partner-controller-get-product",
          label: "Get a partner's shared product",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/partner-controller-get-inventory",
          label: "Get a partner's shared inventory for a product",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/partner-controller-list-documents",
          label: "List a partner's shared documents for a product",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "search",
      items: [
        {
          type: "doc",
          id: "reference/search-controller-search-products",
          label: "Search products",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/search-controller-related",
          label: "Get related products",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/search-controller-resolve",
          label: "Resolve an OSPI code",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "where-to-find",
      items: [
        {
          type: "doc",
          id: "reference/where-to-find-controller-resolve",
          label: "Find where to buy a product",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "offers",
      items: [
        {
          type: "doc",
          id: "reference/offers-controller-create",
          label: "Create a sell-side offer for a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/offers-controller-list-mine",
          label: "List the caller's own offers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/offers-controller-list-for-product",
          label: "List offers for a product",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/offers-controller-withdraw",
          label: "Withdraw an offer",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/offers-controller-set-buyer-minimum",
          label: "Set a per-buyer minimum order quantity override",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/offers-controller-list-buyer-minimums",
          label: "List per-buyer minimum overrides for an offer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/offers-controller-remove-buyer-minimum",
          label: "Remove a per-buyer minimum override",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "orders",
      items: [
        {
          type: "doc",
          id: "reference/orders-controller-create-draft",
          label: "Create a draft order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-list",
          label: "List the caller's orders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/orders-controller-get",
          label: "Get an order by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/orders-controller-add-line",
          label: "Add a line to a draft order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-remove-line",
          label: "Remove a line from a draft order",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/orders-controller-submit",
          label: "Submit a draft order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-accept",
          label: "Accept an order group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-reject",
          label: "Reject an order group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-update-status",
          label: "Update an order group's fulfillment status",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "quotes",
      items: [
        {
          type: "doc",
          id: "reference/quotes-controller-create",
          label: "Create a quote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/quotes-controller-list",
          label: "List the caller's quotes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/quotes-controller-find-one",
          label: "Get a quote by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/quotes-controller-issue",
          label: "Issue a quote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/quotes-controller-accept",
          label: "Accept a quote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/quotes-controller-reject",
          label: "Reject a quote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/quotes-controller-convert",
          label: "Convert an accepted quote into an order",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "dpp",
      items: [
        {
          type: "doc",
          id: "reference/dpp-controller-create-profile",
          label: "Create a DPP profile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-list-profiles",
          label: "List DPP profiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-create-record",
          label: "Create a DPP record for a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-validate",
          label: "Validate a DPP record",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-publish",
          label: "Publish a DPP record",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-suspend",
          label: "Suspend a published DPP record",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-rotate-token",
          label: "Rotate a DPP record's public access token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-get-owner",
          label: "Get a DPP record (owner view)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-get-public",
          label: "Get a public Digital Product Passport",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "webhooks",
      items: [
        {
          type: "doc",
          id: "reference/webhooks-controller-create",
          label: "Create a webhook subscription",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/webhooks-controller-list",
          label: "List webhook subscriptions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/webhooks-controller-remove",
          label: "Delete a webhook subscription",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/webhooks-controller-deliveries",
          label: "List delivery attempts for a subscription",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/webhooks-controller-retry",
          label: "Retry a dead-lettered delivery",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "data-proposals",
      items: [
        {
          type: "doc",
          id: "reference/data-proposals-controller-create",
          label: "Propose a data correction for a product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/data-proposals-controller-list-for-product",
          label: "List data proposals for a product",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/data-proposals-controller-list-mine",
          label: "List the caller's own submitted data proposals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/data-proposals-controller-start-review",
          label: "Start reviewing a data proposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/data-proposals-controller-accept",
          label: "Accept a data proposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/data-proposals-controller-reject",
          label: "Reject a data proposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/data-proposals-controller-withdraw",
          label: "Withdraw a data proposal",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "sso",
      items: [
        {
          type: "doc",
          id: "reference/sso-config-controller-upsert",
          label: "Create/update SSO configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/sso-config-controller-get",
          label: "Get SSO configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/sso-config-controller-remove",
          label: "Remove SSO configuration",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/sso-auth-controller-login",
          label: "Start SSO login",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/sso-auth-controller-oidc-callback",
          label: "OIDC callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/sso-auth-controller-saml-callback",
          label: "SAML callback",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "etim",
      items: [
        {
          type: "doc",
          id: "reference/etim-controller-import-release",
          label: "Import a real ETIM IXF catalog",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "security-monitoring",
      items: [
        {
          type: "doc",
          id: "reference/security-monitoring-controller-list",
          label: "List security alerts",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "branding",
      items: [
        {
          type: "doc",
          id: "reference/branding-controller-create",
          label: "Create a branding profile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/branding-controller-list",
          label: "List the caller's organization's branding profiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/branding-controller-get",
          label: "Get a single branding profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/branding-controller-update",
          label: "Update a branding profile",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/branding-controller-remove",
          label: "Delete a branding profile",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "data-quality",
      items: [
        {
          type: "doc",
          id: "reference/data-quality-controller-get-report",
          label: "Get the caller's own catalogue data-quality report",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "notifications",
      items: [
        {
          type: "doc",
          id: "reference/notifications-controller-list",
          label: "List the caller's organization's notification preferences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/notifications-controller-update",
          label: "Update one category's notification preference",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "reference/schemas/errordetaildto",
          label: "ErrorDetailDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/errorresponsedto",
          label: "ErrorResponseDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/registerdto",
          label: "RegisterDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/logindto",
          label: "LoginDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/refreshdto",
          label: "RefreshDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/switchorganizationdto",
          label: "SwitchOrganizationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/switchentitydto",
          label: "SwitchEntityDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createapiclientdto",
          label: "CreateApiClientDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/confirmmfadto",
          label: "ConfirmMfaDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/disablemfadto",
          label: "DisableMfaDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createroledto",
          label: "CreateRoleDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/assignroledto",
          label: "AssignRoleDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updateorganizationdto",
          label: "UpdateOrganizationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setcommissionratedto",
          label: "SetCommissionRateDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/inviteuserdto",
          label: "InviteUserDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/requestdomainverificationdto",
          label: "RequestDomainVerificationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createentitydto",
          label: "CreateEntityDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updateentitydto",
          label: "UpdateEntityDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createproducerdto",
          label: "CreateProducerDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/issueproducercodedto",
          label: "IssueProducerCodeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/issueospiidentitydto",
          label: "IssueOspiIdentityDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/validatecodedto",
          label: "ValidateCodeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/registerownerdto",
          label: "RegisterOwnerDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createproductdto",
          label: "CreateProductDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/bulkcreateproductdto",
          label: "BulkCreateProductDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updateproductdto",
          label: "UpdateProductDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createvariantdto",
          label: "CreateVariantDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/registerserializedunitdto",
          label: "RegisterSerializedUnitDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/bulkregisterserializedunitdto",
          label: "BulkRegisterSerializedUnitDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/addserializeduniteventdto",
          label: "AddSerializedUnitEventDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setproducttranslationdto",
          label: "SetProductTranslationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createproductrelationshipdto",
          label: "CreateProductRelationshipDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createproductcomponentdto",
          label: "CreateProductComponentDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createproductversiondto",
          label: "CreateProductVersionDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setproductbrandingdto",
          label: "SetProductBrandingDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/upsertcompliancefielddto",
          label: "UpsertComplianceFieldDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createcategorydto",
          label: "CreateCategoryDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/rejectcategorydto",
          label: "RejectCategoryDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setcategorycompliancerequirementdto",
          label: "SetCategoryComplianceRequirementDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createattributedefinitiondto",
          label: "CreateAttributeDefinitionDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setattributevaluedto",
          label: "SetAttributeValueDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createclassificationschemedto",
          label: "CreateClassificationSchemeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createclassificationnodedto",
          label: "CreateClassificationNodeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/assignclassificationdto",
          label: "AssignClassificationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setcategoryattributeschemadto",
          label: "SetCategoryAttributeSchemaDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createattributeschemaproposaldto",
          label: "CreateAttributeSchemaProposalDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/voteonattributeschemaproposaldto",
          label: "VoteOnAttributeSchemaProposalDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/decideattributeschemaproposaldto",
          label: "DecideAttributeSchemaProposalDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createunitcategorydto",
          label: "CreateUnitCategoryDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createunitdto",
          label: "CreateUnitDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createdocumentdto",
          label: "CreateDocumentDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/uploaddocumentdto",
          label: "UploadDocumentDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updatedocumentmetadatadto",
          label: "UpdateDocumentMetadataDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createlocationdto",
          label: "CreateLocationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/upsertinventorydto",
          label: "UpsertInventoryDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/requestconnectiondto",
          label: "RequestConnectionDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/sharingruledto",
          label: "SharingRuleDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createsharinggrantdto",
          label: "CreateSharingGrantDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createpartnerexportdto",
          label: "CreatePartnerExportDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createofferdto",
          label: "CreateOfferDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setofferbuyerminimumdto",
          label: "SetOfferBuyerMinimumDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createdraftorderdto",
          label: "CreateDraftOrderDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/addorderlinedto",
          label: "AddOrderLineDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updateordergroupstatusdto",
          label: "UpdateOrderGroupStatusDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createquotelinedto",
          label: "CreateQuoteLineDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createquotedto",
          label: "CreateQuoteDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createdppprofiledto",
          label: "CreateDppProfileDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createdpprecorddto",
          label: "CreateDppRecordDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createwebhooksubscriptiondto",
          label: "CreateWebhookSubscriptionDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createdataproposaldto",
          label: "CreateDataProposalDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/rejectdataproposaldto",
          label: "RejectDataProposalDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/upsertssoconfigdto",
          label: "UpsertSsoConfigDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createbrandingprofiledto",
          label: "CreateBrandingProfileDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updatebrandingprofiledto",
          label: "UpdateBrandingProfileDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updatenotificationpreferencedto",
          label: "UpdateNotificationPreferenceDto",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
